# Project information
site_name: Datafarmer
site_description: data workers tool
site_author: prasetyo

# Repository information
repo_name: prasetyowahyuaw/datafarmer
repo_url: https://github.com/prasetyowahyuaw/datafarmer

# Configuration
theme:
  name: material
  logo: assets/logo_white.png
  palette:
    - media: "(prefers-color-scheme)"
      primary: light green
      accent: light green
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: light green  
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - content.code.copy
  favicon: assets/logo.png
  font:
      text: Roboto
      code: Roboto Mono

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details

# Pages tree
nav:
  - Getting started: index.md
  - Usage: usage.md

